apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: Cluster
metadata:
  name: dev-cluster
spec:
  clusterNetwork:
    cni: cilium
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    services:
      cidrBlocks:
      - 10.96.0.0/12
  controlPlaneConfiguration:
    count: 3
    endpoint:
      host: 20.13.83.24
    machineGroupRef:
      kind: VSphereMachineConfig
      name: dev-cluster-cp
  datacenterRef:
    kind: VSphereDatacenterConfig
    name: dev-cluster
  kubernetesVersion: "1.20"
  workerNodeGroupConfigurations:
  - count: 3
    machineGroupRef:
      kind: VSphereMachineConfig
      name: dev-cluster

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereDatacenterConfig
metadata:
  name: dev-cluster
spec:
  datacenter: VxRail-Datacenter
  network: Management Network-ed6231d5-efc1-4bd0-8beb-d5c626ab1125
  server: 20.13.83.201
  insecure: false
  thumbprint: 6A:79:A9:2F:59:07:DE:58:77:A4:AF:37:6C:15:7C:BA:41:A0:77:EF

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereMachineConfig
metadata:
  name: dev-cluster-cp
spec:
  datastore: VxRail-Virtual-SAN-Datastore-ed6231d5-efc1-4bd0-8beb-d5c626ab1125
  folder: dev-cluster
  diskGiB: 25
  memoryMiB: 8192
  numCPUs: 2
  osFamily: ubuntu
  template: /VxRail-Datacenter/vm/ubuntu-2004-kube-v1-20-eks-5
  resourcePool: /VxRail-Datacenter/host/VxRail-Virtual-SAN-Cluster-ed6231d5-efc1-4bd0-8beb-d5c626ab1125/Resources
  users:
  - name: capv
    sshAuthorizedKeys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQD2U5DToeUUbH8Gbe8hj9/Rky2iPHabg4iLOjPGYrcOkF4DaBn5lhLJoxlLlqJbUrfLgjvunBdnYzk2U10qJpBEoKO4WmhqRueJocCR3akvJzsKnc/wLeF7Wefq9j9f1JSfIu8LvXWs2f6rrNBcL3hKB2VHMhu+grv9z+wq2wlFktJRB0hbKfoA8XHWmoUgE5HZIQ7taGhChYsuII+MminJ8yR1tnUrxqH7wcy5wzT9Yr0IGD5upUVnqmDZRHx/1vIPeA79Qi2zU1JTCaPE1UCXmsssZ56i46/1Ko/GJO000a+Bk/5CX62HWQF/DeeTKJyj4F+V6+X9+d/JmLHlCAEmz45RYaeWBO+9pUjyKnBAqFf4SzaYlpa9nbq8dkbhhuY/18nauBkhDwwNcSvqgKBZvtLrCdAhunfoYXoGPfpKozIXRCPfiaR56jtjNwhKENVmoTflkvZPZO2jlrV+5gxbweJ0IZFGpJeMnyq03044PlUyzkD8lxGLro4eiDyQUVM= mystic@mystic-virtual-machine

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereMachineConfig
metadata:
  name: dev-cluster
spec:
  datastore: VxRail-Virtual-SAN-Datastore-ed6231d5-efc1-4bd0-8beb-d5c626ab1125
  folder: dev-cluster
  diskGiB: 25
  memoryMiB: 8192
  numCPUs: 2
  osFamily: ubuntu
  template: /VxRail-Datacenter/vm/ubuntu-2004-kube-v1-20-eks-5
  resourcePool: /VxRail-Datacenter/host/VxRail-Virtual-SAN-Cluster-ed6231d5-efc1-4bd0-8beb-d5c626ab1125/Resources
  users:
  - name: capv
    sshAuthorizedKeys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQD2U5DToeUUbH8Gbe8hj9/Rky2iPHabg4iLOjPGYrcOkF4DaBn5lhLJoxlLlqJbUrfLgjvunBdnYzk2U10qJpBEoKO4WmhqRueJocCR3akvJzsKnc/wLeF7Wefq9j9f1JSfIu8LvXWs2f6rrNBcL3hKB2VHMhu+grv9z+wq2wlFktJRB0hbKfoA8XHWmoUgE5HZIQ7taGhChYsuII+MminJ8yR1tnUrxqH7wcy5wzT9Yr0IGD5upUVnqmDZRHx/1vIPeA79Qi2zU1JTCaPE1UCXmsssZ56i46/1Ko/GJO000a+Bk/5CX62HWQF/DeeTKJyj4F+V6+X9+d/JmLHlCAEmz45RYaeWBO+9pUjyKnBAqFf4SzaYlpa9nbq8dkbhhuY/18nauBkhDwwNcSvqgKBZvtLrCdAhunfoYXoGPfpKozIXRCPfiaR56jtjNwhKENVmoTflkvZPZO2jlrV+5gxbweJ0IZFGpJeMnyq03044PlUyzkD8lxGLro4eiDyQUVM= mystic@mystic-virtual-machine

---

